/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatePastOrderRouteImport } from './routes/rate-past-order'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as ProductRecordIdRouteImport } from './routes/product.$recordId'
import { Route as PastOrderOrderIdRouteImport } from './routes/past-order.$orderId'
import { Route as IdentityRegisterRouteImport } from './routes/identity/register'
import { Route as IdentityProfileRouteImport } from './routes/identity/profile'
import { Route as IdentityLoginRouteImport } from './routes/identity/login'
import { Route as IdentityBecomeSellerRouteImport } from './routes/identity/become-seller'
import { Route as BusinessOrdersRouteImport } from './routes/business/orders'
import { Route as BusinessStoreNewRouteImport } from './routes/business/store.new'
import { Route as BusinessStoreStoreIdRouteImport } from './routes/business/store.$storeId'
import { Route as BusinessProductNewRouteImport } from './routes/business/product.new'
import { Route as BusinessProductProductIdRouteImport } from './routes/business/product.$productId'
import { Route as BusinessOrderOrderIdRouteImport } from './routes/business/order.$orderId'

const IndexLazyRouteImport = createFileRoute('/')()

const RatePastOrderRoute = RatePastOrderRouteImport.update({
  id: '/rate-past-order',
  path: '/rate-past-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRecordIdRoute = ProductRecordIdRouteImport.update({
  id: '/product/$recordId',
  path: '/product/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const PastOrderOrderIdRoute = PastOrderOrderIdRouteImport.update({
  id: '/past-order/$orderId',
  path: '/past-order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRegisterRoute = IdentityRegisterRouteImport.update({
  id: '/identity/register',
  path: '/identity/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityProfileRoute = IdentityProfileRouteImport.update({
  id: '/identity/profile',
  path: '/identity/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityLoginRoute = IdentityLoginRouteImport.update({
  id: '/identity/login',
  path: '/identity/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityBecomeSellerRoute = IdentityBecomeSellerRouteImport.update({
  id: '/identity/become-seller',
  path: '/identity/become-seller',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/business/orders',
  path: '/business/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessStoreNewRoute = BusinessStoreNewRouteImport.update({
  id: '/business/store/new',
  path: '/business/store/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessStoreStoreIdRoute = BusinessStoreStoreIdRouteImport.update({
  id: '/business/store/$storeId',
  path: '/business/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProductNewRoute = BusinessProductNewRouteImport.update({
  id: '/business/product/new',
  path: '/business/product/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProductProductIdRoute =
  BusinessProductProductIdRouteImport.update({
    id: '/business/product/$productId',
    path: '/business/product/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessOrderOrderIdRoute = BusinessOrderOrderIdRouteImport.update({
  id: '/business/order/$orderId',
  path: '/business/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/order': typeof OrderRoute
  '/rate-past-order': typeof RatePastOrderRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/identity/become-seller': typeof IdentityBecomeSellerRoute
  '/identity/login': typeof IdentityLoginRoute
  '/identity/profile': typeof IdentityProfileRoute
  '/identity/register': typeof IdentityRegisterRoute
  '/past-order/$orderId': typeof PastOrderOrderIdRoute
  '/product/$recordId': typeof ProductRecordIdRoute
  '/business': typeof BusinessIndexRoute
  '/business/order/$orderId': typeof BusinessOrderOrderIdRoute
  '/business/product/$productId': typeof BusinessProductProductIdRoute
  '/business/product/new': typeof BusinessProductNewRoute
  '/business/store/$storeId': typeof BusinessStoreStoreIdRoute
  '/business/store/new': typeof BusinessStoreNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/order': typeof OrderRoute
  '/rate-past-order': typeof RatePastOrderRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/identity/become-seller': typeof IdentityBecomeSellerRoute
  '/identity/login': typeof IdentityLoginRoute
  '/identity/profile': typeof IdentityProfileRoute
  '/identity/register': typeof IdentityRegisterRoute
  '/past-order/$orderId': typeof PastOrderOrderIdRoute
  '/product/$recordId': typeof ProductRecordIdRoute
  '/business': typeof BusinessIndexRoute
  '/business/order/$orderId': typeof BusinessOrderOrderIdRoute
  '/business/product/$productId': typeof BusinessProductProductIdRoute
  '/business/product/new': typeof BusinessProductNewRoute
  '/business/store/$storeId': typeof BusinessStoreStoreIdRoute
  '/business/store/new': typeof BusinessStoreNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/cart': typeof CartRoute
  '/order': typeof OrderRoute
  '/rate-past-order': typeof RatePastOrderRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/identity/become-seller': typeof IdentityBecomeSellerRoute
  '/identity/login': typeof IdentityLoginRoute
  '/identity/profile': typeof IdentityProfileRoute
  '/identity/register': typeof IdentityRegisterRoute
  '/past-order/$orderId': typeof PastOrderOrderIdRoute
  '/product/$recordId': typeof ProductRecordIdRoute
  '/business/': typeof BusinessIndexRoute
  '/business/order/$orderId': typeof BusinessOrderOrderIdRoute
  '/business/product/$productId': typeof BusinessProductProductIdRoute
  '/business/product/new': typeof BusinessProductNewRoute
  '/business/store/$storeId': typeof BusinessStoreStoreIdRoute
  '/business/store/new': typeof BusinessStoreNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/order'
    | '/rate-past-order'
    | '/business/orders'
    | '/identity/become-seller'
    | '/identity/login'
    | '/identity/profile'
    | '/identity/register'
    | '/past-order/$orderId'
    | '/product/$recordId'
    | '/business'
    | '/business/order/$orderId'
    | '/business/product/$productId'
    | '/business/product/new'
    | '/business/store/$storeId'
    | '/business/store/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/order'
    | '/rate-past-order'
    | '/business/orders'
    | '/identity/become-seller'
    | '/identity/login'
    | '/identity/profile'
    | '/identity/register'
    | '/past-order/$orderId'
    | '/product/$recordId'
    | '/business'
    | '/business/order/$orderId'
    | '/business/product/$productId'
    | '/business/product/new'
    | '/business/store/$storeId'
    | '/business/store/new'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/order'
    | '/rate-past-order'
    | '/business/orders'
    | '/identity/become-seller'
    | '/identity/login'
    | '/identity/profile'
    | '/identity/register'
    | '/past-order/$orderId'
    | '/product/$recordId'
    | '/business/'
    | '/business/order/$orderId'
    | '/business/product/$productId'
    | '/business/product/new'
    | '/business/store/$storeId'
    | '/business/store/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CartRoute: typeof CartRoute
  OrderRoute: typeof OrderRoute
  RatePastOrderRoute: typeof RatePastOrderRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  IdentityBecomeSellerRoute: typeof IdentityBecomeSellerRoute
  IdentityLoginRoute: typeof IdentityLoginRoute
  IdentityProfileRoute: typeof IdentityProfileRoute
  IdentityRegisterRoute: typeof IdentityRegisterRoute
  PastOrderOrderIdRoute: typeof PastOrderOrderIdRoute
  ProductRecordIdRoute: typeof ProductRecordIdRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  BusinessOrderOrderIdRoute: typeof BusinessOrderOrderIdRoute
  BusinessProductProductIdRoute: typeof BusinessProductProductIdRoute
  BusinessProductNewRoute: typeof BusinessProductNewRoute
  BusinessStoreStoreIdRoute: typeof BusinessStoreStoreIdRoute
  BusinessStoreNewRoute: typeof BusinessStoreNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rate-past-order': {
      id: '/rate-past-order'
      path: '/rate-past-order'
      fullPath: '/rate-past-order'
      preLoaderRoute: typeof RatePastOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$recordId': {
      id: '/product/$recordId'
      path: '/product/$recordId'
      fullPath: '/product/$recordId'
      preLoaderRoute: typeof ProductRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-order/$orderId': {
      id: '/past-order/$orderId'
      path: '/past-order/$orderId'
      fullPath: '/past-order/$orderId'
      preLoaderRoute: typeof PastOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/register': {
      id: '/identity/register'
      path: '/identity/register'
      fullPath: '/identity/register'
      preLoaderRoute: typeof IdentityRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/profile': {
      id: '/identity/profile'
      path: '/identity/profile'
      fullPath: '/identity/profile'
      preLoaderRoute: typeof IdentityProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/login': {
      id: '/identity/login'
      path: '/identity/login'
      fullPath: '/identity/login'
      preLoaderRoute: typeof IdentityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/become-seller': {
      id: '/identity/become-seller'
      path: '/identity/become-seller'
      fullPath: '/identity/become-seller'
      preLoaderRoute: typeof IdentityBecomeSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/business/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/store/new': {
      id: '/business/store/new'
      path: '/business/store/new'
      fullPath: '/business/store/new'
      preLoaderRoute: typeof BusinessStoreNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/store/$storeId': {
      id: '/business/store/$storeId'
      path: '/business/store/$storeId'
      fullPath: '/business/store/$storeId'
      preLoaderRoute: typeof BusinessStoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/product/new': {
      id: '/business/product/new'
      path: '/business/product/new'
      fullPath: '/business/product/new'
      preLoaderRoute: typeof BusinessProductNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/product/$productId': {
      id: '/business/product/$productId'
      path: '/business/product/$productId'
      fullPath: '/business/product/$productId'
      preLoaderRoute: typeof BusinessProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/order/$orderId': {
      id: '/business/order/$orderId'
      path: '/business/order/$orderId'
      fullPath: '/business/order/$orderId'
      preLoaderRoute: typeof BusinessOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CartRoute: CartRoute,
  OrderRoute: OrderRoute,
  RatePastOrderRoute: RatePastOrderRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
  IdentityBecomeSellerRoute: IdentityBecomeSellerRoute,
  IdentityLoginRoute: IdentityLoginRoute,
  IdentityProfileRoute: IdentityProfileRoute,
  IdentityRegisterRoute: IdentityRegisterRoute,
  PastOrderOrderIdRoute: PastOrderOrderIdRoute,
  ProductRecordIdRoute: ProductRecordIdRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  BusinessOrderOrderIdRoute: BusinessOrderOrderIdRoute,
  BusinessProductProductIdRoute: BusinessProductProductIdRoute,
  BusinessProductNewRoute: BusinessProductNewRoute,
  BusinessStoreStoreIdRoute: BusinessStoreStoreIdRoute,
  BusinessStoreNewRoute: BusinessStoreNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
